### ISSUE TITLE
flutter_driver from sdk is incompatible with web_socket_channel 2.0.0

### ISSUE THREAD

**Issue by BarteeX** [dart-lang/http#1497]
Hello,

After upgrade to flutter 2.0 null safety I've encountered an error in the application.

`pub upgrade`

```
Because every version of flutter_driver from sdk depends on crypto 2.1.5 and web_socket_channel 2.0.0 depends on crypto ^3.0.0, flutter_driver from sdk is incompatible with web_socket_channel 2.0.0.
And because no versions of web_socket_channel match >2.0.0 <3.0.0, flutter_driver from sdk is incompatible with web_socket_channel ^2.0.0.
So, because XXX depends on both web_socket_channel ^2.0.0 and flutter_driver any from sdk, version solving failed.
pub get failed (1; So, because XXX depends on both web_socket_channel ^2.0.0 and flutter_driver any from sdk, version solving failed.)
```

```
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ...
  web_socket_channel: ^2.0.0
  ...

dev_dependencies:
  ...
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
```

```
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19041.388], locale pl-PL)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
[√] Connected device (2 available)
```
