### ISSUE TITLE
Conflict package build_runner versions

### ISSUE THREAD

**Issue by jttuboi** [dart-lang/http#1685]
When I run:

```bash
~$ flutter clean; flutter pub get;
Cleaning Xcode workspace...                                      1,346ms
Resolving dependencies... (1.4s)
Because build_runner >=2.0.0 depends on web_socket_channel ^2.0.0 and gris_app_flutter depends on web_socket_channel ^3.0.0, build_runner >=2.0.0 is forbidden.
So, because gris_app_flutter depends on build_runner ^2.4.9, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on web_socket_channel: flutter pub add web_socket_channel:^2.4.5
```

> pupspec.yaml
```yaml

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: "3.19.6"

dependencies:
  ...
  web_socket_channel: ^3.0.0

dev_dependencies:
  ...
  build_runner: ^2.4.9
```
