### ISSUE TITLE
Not support cookie!

### ISSUE THREAD

**Issue by jaggerwang** [dart-lang/http#170]
## Problem

I'm surprised to found that this http client library does not support cookie! And I googled a lot, still not get a good way to handle this problem.

## Code

```dart
import 'dart:convert';
import 'dart:io';
import 'dart:async';
import 'package:http/http.dart' as http;
import 'package:uri/uri.dart';
import 'package:logging/logging.dart';

import '../config.dart';

class TangboleService {
  final TangboleConfig config;
  final Logger logger;
  final http.Client client = http.Client();

  TangboleService(this.config, this.logger);

  Future<TangboleApiResponse> get(
    String path, {
    Map<String, String> params = const {},
    Duration duration = const Duration(seconds: 10),
  }) async {
    final uri = UriBuilder.fromUri(Uri.parse(config.tangboleApiBaseUrl));
    uri.path += path;
    uri.queryParameters = params;

    final url = uri.build();
    http.Response response;
    try {
      response = await client.get(url).timeout(duration);
    } catch (e) {
      final r = TangboleApiResponse(
          TangboleApiResponseCode.request_timeout, e.toString(), null);
      logger.severe('url: $url, response: $r');
      return r;
    }

    if (response.statusCode == HttpStatus.OK) {
      final r = TangboleApiResponse.fromJson(json.decode(response.body));
      logger.fine('url: $url, response: $r');
      return r;
    } else {
      final r = TangboleApiResponse(
          TangboleApiResponseCode.response_status_not_ok,
          response.statusCode.toString(),
          null);
      logger.warning('url: $url, response: $r');
      return r;
    }
  }

  Future<TangboleApiResponse> post(
    String path, {
    Map<String, String> params = const {},
    Duration duration = const Duration(seconds: 10),
  }) async {
    final uri = UriBuilder.fromUri(Uri.parse(config.tangboleApiBaseUrl));
    uri.path += path;

    final url = uri.build();
    final body = json.encode(params);
    http.Response response;
    try {
      response = await client
          .post(
            url,
            headers: {HttpHeaders.CONTENT_TYPE: ContentType.JSON.toString()},
            body: body,
          )
          .timeout(duration);
    } catch (e) {
      final r = TangboleApiResponse(
          TangboleApiResponseCode.request_timeout, e.toString(), null);
      logger.severe('url: $url, body: $body, response: $r');
      return r;
    }

    if (response.statusCode == HttpStatus.OK) {
      final r = TangboleApiResponse.fromJson(json.decode(response.body));
      logger.fine('url: $url, body: $body, response: $r');
      return r;
    } else {
      final r = TangboleApiResponse(
          TangboleApiResponseCode.response_status_not_ok,
          response.statusCode.toString(),
          null);
      logger.warning('url: $url, body: $body, response: $r');
      return r;
    }
  }

  Future<TangboleApiResponse> login(String username, String password) {
    return post('/account/login',
        params: {'username': username, 'password': password});
  }

  Future<TangboleApiResponse> getAccount() {
    return get('/account/info');
  }

class TangboleApiResponse {
  final int code;
  final String message;
  final Map<String, dynamic> data;

  TangboleApiResponse(this.code, this.message, this.data);

  static TangboleApiResponse fromJson(dynamic json) {
    return TangboleApiResponse(json['code'], json['message'], json['data']);
  }

  @override
  String toString() =>
      'TangboleApiResponse(code: $code, message: $message, data: $data)';
}

class TangboleApiResponseCode {
  static const int ok = 0;
  static const int server_internal_error = -1;
  static const int request_timeout = -2;
  static const int response_status_not_ok = -3;
}
```

After calling `'/account/login` api, I can't get logined user info by `'/account/info` api. I'm already test ed the apis using Postman tool.

<img width="1392" alt="2018-06-24 18 01 42" src="https://user-images.githubusercontent.com/1255011/41818012-de0e0cd6-77d8-11e8-90a4-bac5e47e983e.png">
<img width="1392" alt="2018-06-24 18 02 23" src="https://user-images.githubusercontent.com/1255011/41818013-de5eda3a-77d8-11e8-9eef-84df74e37416.png">

## Env

```yaml
name: tangbole
description: A tumblr client app.

dependencies:
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  flutter:
    sdk: flutter
  flutter_redux: ^0.5.1
  http: ^0.11.3+16
  logging: ^0.11.3+1
  meta: ^1.1.5
  uri: ^0.11.2
  redux: ^3.0.0
  redux_logging: ^0.3.0
  redux_persist: ^0.7.0-rc.2
  redux_persist_flutter: ^0.6.0-rc.1
  validate: ^1.6.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^2.2.3

flutter:
  uses-material-design: true
  assets:
    - images/lake.jpg

```
