### ISSUE TITLE
unable to connect to 10.0.2.2

### ISSUE THREAD

**Issue by steelx** [dart-lang/http#466]
Everything was working fine, until today I did `flutter upgrade`.

I have a dart backend service running at `0.0.0.0:8080` If I hit my backend API from postman it responds fine, but doesnt respond to any flutter calls, seem flutter is not making any calls at all. But when I did console log to my api client, this was flutter print, but backend didn't receive any request.

No matter which API_ENDPOINT I pass it fails everytime, but from emulator chrome I can made those requests fine.

```
I/flutter ( 6513): POST: http://10.0.2.2:8080/login
I/flutter ( 6513): error ------>>>>> Error: Password wont match!
```

Now My flutter app wont connect to my localhost server at API_ENDPOINT:
`const API_ENDPOINT = String.fromEnvironment('API_ENDPOINT', defaultValue: 'http://10.0.2.2:8080');`

When I run this locally I do not pass any env variable and hence it should pickup `10.0.2.2`.

**flutter doctor -v** :
```bash

PS C:\Users\ajink> flutter doctor -v
[✓] Flutter (Channel master, 1.22.0-2.0.pre.135, on Microsoft Windows [Version 10.0.19041.450], locale en-IN)
    • Flutter version 1.22.0-2.0.pre.135 at C:\src\flutter
    • Framework revision 8fa5c55e54 (10 hours ago), 2020-08-30 19:05:20 -0700
    • Engine revision 1e302a111d
    • Dart version 2.10.0 (build 2.10.0-76.0.dev)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\ajink\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.5.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.5.30011.22
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code, 64-bit edition (version 1.47.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.13.1

[✓] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 83.0.4103.116
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 84.0.522.63

• No issues found!
```

and here is the **pubspec** file:
```yml
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  rxdart: ^0.24.1
  provider: ^4.1.3
  http: ^0.12.2
  sqflite: ^1.3.1
  path_provider: ^1.6.11
  flutter_secure_storage: ^3.3.3
  fluttertoast: ^7.0.2
  flutter_svg: ^0.18.0
  common:
    path: ./common
  video_player:
  webview_flutter: ^0.3.22+1
  flutter_local_notifications: ^1.4.4+2
  shared_preferences:
  printing: 3.5.0
  pdf: 1.9.0
  numberpicker: ^1.2.1
  camera:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.1
  network_image_mock: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/images/monthly_move_resources/
```

its just a simple http GET, POST call.... but if I do the same from Emulators Chrome browser GET call works fine.
it seems it just the app not able to find `10.0.2.2` or any-other external API as well happens only on Windows os.

I have made a video from Windows and MAC OS showing how it doesn't work on Windows :
https://youtu.be/Mp6ginVgLiI
