### ISSUE TITLE
🐛 Cannot send HTTP with Bearer Authentication: ClientException (Failed to parse header value) 

### ISSUE THREAD

**Issue by AdrKacz** [dart-lang/http#821]
# 🐛 Cannot send HTTP with Bearer Authentication: ClientException (Failed to parse header value) 

I want to POST and GET an HTTP API that requires *JWT* authentication.

However, when I launch the request, it immediately fires **ClientException (Failed to parse header value)**.

The locals in the error stack are:
```
request: Request (GET https://api-endpoint/status)
headers: _CompactLinkedCustomHashMap ({content-type: application/json, authorization: Bearer XXX})
```

I send the request with the following `dart` code:
```dart
await http.get(Uri.parse('https://api-endpoint/status'), headers: {
      HttpHeaders.contentTypeHeader: 'application/json',
      HttpHeaders.authorizationHeader: 'Bearer XXX'
    });
```

However, I had no issue testing the request using [hoppscotch.io](https://hoppscotch.io). I received the expected result without error. Here is the request sent by [hoppscotch.io](https://hoppscotch.io):
```sh
curl --request GET \
  --url https://api-endpoint/status \
  --header 'Authorization: Bearer XXX'
```

Any help will be appreciated 😁

### Flutter doctor
```sh
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0.1 22A400 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.73.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

### Pubspec dependencies
```yaml
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  flutter_chat_ui: ^1.6.6
  web_socket_channel: ^2.2.0
  uuid: ^3.0.6
  http: ^0.13.5
  firebase_core: ^2.2.0
  firebase_messaging: ^14.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.1.6
  badges: ^2.0.3
  yaml: ^3.1.1
  pointycastle: ^3.6.2
  asn1lib: ^1.2.2
  image_picker: ^0.8.6
  permission_handler: ^10.2.0
  image_cropper: ^3.0.1
  flutter_email_sender: ^5.1.0
  path_provider: ^2.0.11
```
